name: Sync README.md file

on:
  push:
    paths:
      - profile/README.md

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copy profile README.md file to root directory
        run: cp profile/README.md README.md

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "doc: sync root README.md file from profile README.md file" || exit 0
          git push
